# Generated by Django 4.0.4 on 2022-05-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecDevolucion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecPrestamo',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecPrestamo', models.DateField()),
                ('fecDevolucion', models.DateField()),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
    ]
