# Generated by Django 4.0.4 on 2022-05-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_prestamos_fecdevolucion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
